version: '3.8'

services:

  backend:
    container_name: project_icm
    platform: linux/amd64
    depends_on:
      - db
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./.env
  
  db:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '139700'
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: